### ISSUE TITLE
PLP navigation

### ISSUE THREAD

**Issue by chris-steele** [cgkineo/adapt-scrollSnap#19]
Using PLP to navigate to blocks doesn't work if the plugin isn't explicitly enabled for the page. https://github.com/cgkineo/adapt-scrollSnap/blob/master/js/Page.js#L75 interprets `undefined` as `false`, though editing this line isn't the entire solution: navigation is fixed but a runtime error occurs.

**Comment by oliverfoster** [comment]
works for me in latest version
